### ISSUE TITLE
You must provide an API key

### ISSUE THREAD

**Issue by vkarakaya** [drone-plugins/drone-gitea-release#20]
```gitea_release:
    image: plugins/gitea-release
    settings:
        base_url: http://gidro.westeurope.cloudapp.azure.com:3000
        api_key:
          from_secret: gitea_token
        files: .*.tar.gz
    checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
        event: tag
```

not working?
![image](https://user-images.githubusercontent.com/37079672/58763923-dd28a700-8569-11e9-82ab-1ad7b95aac42.png)

compose file 
```
version: "3.7"


services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
  drone-server:
    image: drone/drone:1
    container_name: drone_server
    networks:
      - dronenet
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /var/lib/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_PROTO=http 
      - DRONE_SERVER_HOST=gidro.westeurope.cloudapp.azure.com:8080
      - DRONE_TLS_AUTOCERT=false 

networks:
  dronenet:
```

**Comment by tboerger** [comment]
I'm using this plugin on a daily base, I can't confirm any issue as long as you configured the secrets and drone correctly.

**Comment by tboerger** [comment]
You files setting won't work, it got to be a glob and not a regular expression.

**Comment by tboerger** [comment]
Closing because of lacking details

**Comment by cooperspencer** [comment]
@tboerger I have the same problem. I get `
time="2019-08-19T12:56:28Z" level=fatal msg="You must provide an API key"` as well.
With API-Key I hope you mean the gitea-token? Because otherwise I've done something completely wrong

**Comment by tboerger** [comment]
If you don't provide the gitea api key it can't work.

**Comment by cooperspencer** [comment]
I generated the key according to this documentation:
`https://docs.gitea.io/en-us/api-usage/`

But it still says I have to provide an API key.

`
  PUSH:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://buddyspencer.duckdns.org/gitea
      files: gohome
    when:
      event: tag
`

**Comment by cooperspencer** [comment]
I generated the key according to this documentation:
[gitea](https://docs.gitea.io/en-us/api-usage/)

But it still says I have to provide an API key.
```
  PUSH:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://xxx/gitea
      files: gohome
    when:
      event: tag
```
