### ISSUE TITLE
Failed to create release: title is empty

### ISSUE THREAD

**Issue by volker-raschek** [drone-plugins/drone-gitea-release#26]
Hello, 
my colleagues and I use this plugin to upload generated pdf files compiled with latex in a release build. Since the upgrade of gitea to 1.13.0 we receive the following error: `Failed to create release: title is empty`.

### More details

To release a version of a latex document we use in general the following git commands. For example to release a pdf document in version v0.1.0.
 
```bash
$ git tag -a v0.1.0 -m v0.1.0 
$ git push origin v0.1.0 
```

When the tag has been successfully pushed onto the git repository hosted on a gitea instance the following drone step will be started as one of others to push the release.

```yaml
- name: push-tagged-gitea
  image: plugins/gitea-release
  settings:
    base_url: https://git.cryptic.systems
    api_key:
      from_secret: gitea_token
    files:
    - index.pdf
    checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    repo:
    - fh-trier/klinux_ws2021
    event:
    - tag
```

The step returns the following error:

```txt
Release v0.1.0 not found
time="2021-01-30T13:06:57Z" level=fatal msg="Failed to create the release. Failed to retrieve or create a release: Failed to create release: title is empty"
```

Now, why this does not work any more to release a compiled pdf document with the new version of gitea 13.0.0?

I tested additionally to release a new version over the web interface of gitea. There I must define a title for the release. I use v0.1.0 as title and the release step runs successfully. I'm kind of surprised that it works through the GUI but not through the CLI via git. Are we doing something wrong or is this the problem with the plugin?

**Comment by tboerger** [comment]
If it worked before it sounds like Gitea has changed the requirements. Maybe it has not required ta title before?

**Comment by khozaei** [comment]
I had this problem too. I found solution for it. You can add `title`  to `.drone.yml` file like below:
```yml
- name: push-tagged-gitea
  image: plugins/gitea-release
  settings:
    base_url: https://git.cryptic.systems
    api_key:
      from_secret: gitea_token
    files:
    - index.pdf
    title: release
    checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    repo:
    - fh-trier/klinux_ws2021
    event:
    - tag
```
It works for me.
