### ISSUE TITLE
Can't create release - 403 Forbidden

### ISSUE THREAD

**Issue by zaphbbrox** [drone-plugins/drone-gitea-release#36]
When trying to create a release, the plugin always shows:
    
    level=fatal msg="403 Forbidden"

In the gitea log:

    router: completed GET /api/v1/version for 192.168.80.2:0, 403 Forbidden in 2.9ms @ context/auth.go:113(context.ToggleAPI)

The secret is properly set in the UI.
The config:
```
  release:
    image: plugins/gitea-release
    environment:
      - DRONE_REPO_OWNER=${CI_REPO_OWNER}
      - DRONE_REPO_NAME=${CI_REPO_NAME}
      - DRONE_BUILD_EVENT=${CI_BUILD_EVENT}
      - DRONE_COMMIT_REF=${CI_COMMIT_REF}
    settings:
      api_key:
        - from_secrets: GITEA_API_KEY
      base_url: https://git.example.com
      files: dist/${CI_REPO_NAME}-${CI_COMMIT_TAG}.zip
      file_exists: fail
      prerelease: true
      title: ${CI_COMMIT_TAG}
    when:
      event: tag
      tag: v*
``` 
We already tried to add the `GITEA_API_KEY` to environment (as `API_KEY`, as well as `PLUGIN_API_KEY`) and add `secrets: [GITEA_API_KEY]` to the config.  
Also we tried to using a public, user owned repository, instead of a private, organisation repository. 

Any help is much appreciated!
