### ISSUE TITLE
404 Not Found - Error

### ISSUE THREAD

**Issue by Sharrnah** [drone-plugins/drone-gitea-release#43]
I am using this plugin for some time now. I changed from gitea to forgejo but i don't believe this is the reason because Forgejo should be backwards compatible.

When trying to use the Plugin i am always getting the error
`time="2024-09-16T16:05:01Z" level=fatal msg="404 Not Found"`

Its not a really helpful error message, But my current guess is that for some reason, it can't find the Docker image, because using other Docker images from docker hub work without issues.

```yaml
---
kind: pipeline
type: kubernetes
name: build

steps:
# ...

  - name: git-release-linux
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: docker_password
      base_url: ${DRONE_REPO_LINK}
      files:
        - '/drone/src/Release.tar.xz'
    when:
      event:
        - tag
    depends_on:
      - build-linux
```
