### ISSUE TITLE
Failed to create release: unexpected end of JSON input

### ISSUE THREAD

**Issue by rigelk** [drone-plugins/drone-gitea-release#7]
```
Release TAG not found
time="2018-05-23T17:32:48Z" level=fatal msg="Failed to create the release. Failed to retrieve or create a release: Failed to create release: unexpected end of JSON input"
```

I've looked through the issue but am not sure how to interpret this. What could lead to this error?

**Comment by jonasfranz** [comment]
Which version of gitea are you using?

**Comment by volker-raschek** [comment]
I Have the same error!
```
Release v0.0.6 not found
time="2018-07-20T15:27:45Z" level=fatal msg="Failed to create the release. Failed to retrieve or create a release: Failed to create release: unexpected end of JSON input" 
```
My versions
drone-server: 0.8
drone-agent: 0.8
gitea: b37ca4a

my `drone.yml`
```
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  generate_pdf:
    image: volkerraschek/docker-latex:latest
    pull: true
    commands:
    - make

  gitea_release:
    image: plugins/gitea-release
    base_url: https://git.cryptic.systems
    api_key: [ key ]
    files: index.pdf
    when:
      event: [ tag ]

  github_push:
    image: appleboy/drone-git-push
    pull: true
    secrets: [ git_push_ssh_key ]
    remote: git@github.com:volker-raschek/zgoe_ss18.git
    force: true
    when:
      event: [ push ]
      branch: [ master ]
```

**Comment by jonasfranz** [comment]
@volker-raschek You are usung an invalid secret name. Please use the secret name documented here: 
http://plugins.drone.io/drone-plugins/drone-gitea-release/

**Comment by volker-raschek** [comment]
I've set now in drone the secret named `gitea_token` in my repository with the a token from gitea. But I get know the following error.

```
Successfully created v0.0.4 release
time="2018-07-22T19:57:49Z" level=fatal msg="Failed to upload the files. Failed to upload index.pdf artifact: invalid character '<' looking for beginning of value"
```

My `.drone.yml`
```
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  generate_pdf:
    image: volkerraschek/docker-latex:latest
    pull: true
    commands:
    - make

  gitea_release:
    image: plugins/gitea-release
    base_url: https://git.cryptic.systems
    secrets: [ gitea_token ]
    files: index.pdf
    when:
      event: [ tag ]
```

**Comment by jonasfranz** [comment]
@volker-raschek Please also provide your `app.ini` for further investigation.

**Comment by volker-raschek** [comment]
My app.ini

```
APP_NAME = Cryptic Systems
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.upload]
TEMP_PATH = /data/gitea/uploads

[server]
APP_DATA_PATH    = /data/gitea
DOMAIN           = git.cryptic.systems
ROOT_URL         = https://git.cryptic.systems/
HTTP_PORT        = 3000
SSH_DOMAIN       = git.cryptic.systems
SSH_PORT         = 10022
DISABLE_SSH      = false
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/gitea/lfs
LFS_JWT_SECRET   = <MyLFSSecrect>
OFFLINE_MODE     = false

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = localhost:3306
NAME     = gitea
USER     = root
PASSWD   =
SSL_MODE = disable

[session]
PROVIDER_CONFIG = /data/gitea/sessions
PROVIDER        = file

[picture]
AVATAR_UPLOAD_PATH      = /data/gitea/avatars
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[attachment]
PATH = /data/gitea/attachments

[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = Info

[security]
INSTALL_LOCK   = true
SECRET_KEY     = <seckey>
INTERNAL_TOKEN = <token>

[service]
REGISTER_EMAIL_CONFIRM            = true
ENABLE_NOTIFY_MAIL                = true
DISABLE_REGISTRATION              = true
ENABLE_CAPTCHA                    = true
REQUIRE_SIGNIN_VIEW               = false
DEFAULT_KEEP_EMAIL_PRIVATE        = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.example.org

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false
```

**Comment by jonasfranz** [comment]
> ```ini
> [attachment]
> PATH = /data/gitea/attachments
> ```
> --- @volker-raschek 

Your `attachment` section does not allow it to upload pdf documents. Please make sure to allow the mime type by following the [config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment) provided at the Gitea documentation.

**Comment by tboerger** [comment]
@jonasfranzdev but in that case we must improve the error message... This is absolutely misleading.

**Comment by volker-raschek** [comment]
I get the same error.
```
Release v0.0.12 not found
Successfully created v0.0.12 release
time="2018-07-23T16:25:08Z" level=fatal msg="Failed to upload the files. Failed to upload index.pdf artifact: invalid character '<' looking for beginning of value"
```

My changed app.ini (docker container)
```
[attachment]
ENABLED       = true
PATH          = /data/gitea/attachments
MAX_SIZE      = 10
ALLOWED_TYPES = */*
```
My folder for attachments with permissions
```
root@vm087: # ls -la ~/docker/gitea/data/gitea/attachments/
insgesamt 8
drwxr-xr-x 2 user001 user001 4096 Jul 23 18:21 .
drwxr-xr-x 9 user001 user001 4096 Jul 23 18:25 ..
```

**Comment by jonasfranz** [comment]
@volker-raschek Is your file >= 10MB?

**Comment by volker-raschek** [comment]
No, it's not bigger than 10MB
```
markus@markus-pc:~/workspace/ARCHIVE/zgeo_ss18 (master=)$ ls -lh index.pdf 
-rw-r--r-- 2 markus markus 2,5M 19. Jul 21:42 index.pdf
```

**Comment by tboerger** [comment]
Are you able to reproduce the issue with try.gitea.io and drone.try.gitea.io?

**Comment by volker-raschek** [comment]
At the moment is try.gitea.io down. 
I would like to reproduce the issue the next days.

**Comment by volker-raschek** [comment]
So, 
I have created a new repository on try.gitea.io: https://try.gitea.io/volker.raschek/zgeo_ss18

When I want to login into drone.try.gitea.io with my credentials, I get the following login error 

```The system failed to process your Login request.```

At the moment I can not reproduce the issue on drone.try.gitea.io, because I can not login into the drone system.

**Comment by vbrandl** [comment]
I'm getting the same error. Did you get to reproduce the issue?

**Comment by endeav0r** [comment]
I got the same error.

* Made sure I was using a https URL. This is an internal server without internet, so I had to set `insecure: true`.
* Set up `[attachment]` appropriately.

```
- name: gitea-release
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: drone-builds
    base_url: https://10.1.2.3
    insecure: true
    files: dist/*
    checksum:
      - sha1
      - sha256
  when:
    event: tag
```

```
[attachment]
PATH = /var/lib/gitea/attachment
ENABLED = true
ALLOWED_TYPES = */*
MAX_SIZE = 8
MAX_FILES = 16
```

I then upgraded from Gitea 1.7.1 to 1.7.4

I uploaded a file via the web interface and successfully downloaded it.

From what I can tell this plugin is broken against latest, stable Gitea.

**Comment by bradrydzewski** [comment]
`invalid character '<' looking for beginning of value` could also indicate networking problem. The `<` generally indicates the http request expects json but gets an html page that starts with `<html`...

so why would an API request get an html document as a response? It is almost always network related. For example, a reverse proxy server that is not correctly routing the request, or perhaps an http to https auto-redirect that changes the request from a POST to a GET and strips the request body.

**Comment by iddm** [comment]
> invalid character '<' looking for beginning of value could also indicate networking problem. The < generally indicates the http request expects json but gets an html page that starts with <html...

We should have much more definitive and clear error description, to avoid making guesses and actually fixing the problem. Here we had to create this issue, to spend a year discussing it, and still I also have just got this error.

**Comment by tboerger** [comment]
This error indicates that you have not yet the right target url. This plugin itself is working totally fine like it is, and I'm using that with stable releases on a daily base.

**Comment by iddm** [comment]
I was talking specifically about the `<` problem:


```
1 | Release 0.1.4 not found
-- | --
2 | Successfully created 0.1.4 release
3 | time="2019-07-26T21:26:47Z" level=fatal msg="Failed to upload the files. Failed to upload target/x86_64-unknown-linux-musl/release/binary artifact: invalid character '<' looking for beginning of value"
```

I don't think I have an idea of what was wrong.

**Comment by tboerger** [comment]
The plugin tries to communicate with the gitea api, which responds with json, maybe you configured the wrong url, or you configured http and the server redirects to https, in that case the plugin can't parse the response, which leads to this error. 

I don't know any way to properly handle that.

**Comment by iddm** [comment]
All of the things you have mentioned are "maybe". I am talking here about making this message more clear.

Also, no, the `base_url` parameter is absolutely correct, the key in secrets in absolutely correct.

```yaml
- name: gitea-release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_release_plugin_token
    base_url: https://git.lalala.com
    files:
      - target/x86_64-unknown-linux-musl/release/binary
  checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    event: 
    - tag
```

Gitea: 1.9.0+dev-300-g57b2ce03d
Drone: 1.0

It is even shown that the token was used by the drone gitea release plugin:

![](https://i.imgur.com/DaXbDrw.png)
