### ISSUE TITLE
Failed to fetch existing assets

### ISSUE THREAD

**Issue by vbrandl** [drone-plugins/drone-gitea-release#8]
I'm trying to push my build artifacts back into my Gitea 1.4.2 instance using the following configuration:

```yml
  release:
    image: plugins/gitea-release
    base_url: https://example.com
    secrets: [ gitea_token ]
    files:
      - target/x86_64-unknown-linux-musl/drone-test
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    when:
      event: tag
```

The new release is created, but before uploading the new assets, the plugin fails when trying to fetch the existing assets: 
`Failed to upload the files. Failed to fetch existing assets: 404 Not Found`

Did the Gitea API change?
